### ISSUE TITLE
Application crashes during start (progress 0%)

### ISSUE THREAD

**Issue by tomikmar** [shymmq/librus-client#119]
When I start the app, I receive "Wystąpił nieoczekiwany błąd" and application shows progress 0%.

Version: 1.2r from F-Droid

Here is the application log:
[librus-2017-04-22.txt](https://github.com/shymmq/librus-client/files/948916/librus-2017-04-22.txt)

**Comment by xdk78** [comment]
F-Droid version its currenty not supported.
Try this: https://play.google.com/store/apps/details?id=pl.librus.client

**Comment by shymmq** [comment]
This bug was fixed in https://github.com/shymmq/librus-client/commit/4ac86b2df9560fb28e1a280c4762760694d19c97

**Comment by tomikmar** [comment]
I checked on F-Droid and I created a ticket:
* https://gitlab.com/fdroid/fdroiddata/issues/708

It looks that tags are detected correctly, but F-Droid build doesn't start for unknown reason.

**Comment by tomikmar** [comment]
Problem with starting build on F-Droid was resolved: https://gitlab.com/fdroid/admin/issues/28

Right now we have an issue during compilation:
- https://f-droid.org/wiki/page/pl.librus.client/lastbuild_13

**Comment by mimi89999** [comment]
It was solved by my commit.

**Comment by tomikmar** [comment]
> This bug was fixed in 4ac86b2

I am not sure if it is solved. I have the latest build from F-Droid (1.5r) and it doesn't start:
```
06-03 22:57:15.917 29621 29621 D librus-client-log: Handle update error
06-03 22:57:15.917 29621 29621 E librus-client-log: Unknown error
06-03 22:57:15.917 29621 29621 W System.err: pl.librus.client.data.server.HttpException: Request to URL https://api.librus.pl/2.0/LuckyNumbers failed with code 403 and message: {"Status":"Error","Code":"LuckyNumberIsNotActive","Message":"Lucky number is not active.","Resources":{"..":{"Url":"https:\/\/api.librus.pl\/2.0\/Root"}},"Url":"https:\/\/api.librus.pl\/2.0\/LuckyNumbers"}
06-03 22:57:15.917 29621 29621 W System.err: 	at pl.librus.client.data.server.RxHttpClient.createException(RxHttpClient.java:57)
06-03 22:57:15.917 29621 29621 W System.err: 	at pl.librus.client.data.server.RxHttpClient.lambda$executeCall$0(RxHttpClient.java:43)
06-03 22:57:15.917 29621 29621 W System.err: 	at pl.librus.client.data.server.RxHttpClient$$Lambda$1.subscribe(Unknown Source)
06-03 22:57:15.917 29621 29621 W System.err: 	at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
06-03 22:57:15.917 29621 29621 W System.err: 	at io.reactivex.Single.subscribe(Single.java:2703)
06-03 22:57:15.917 29621 29621 W System.err: 	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
06-03 22:57:15.917 29621 29621 W System.err: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
06-03 22:57:15.917 29621 29621 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
06-03 22:57:15.917 29621 29621 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
06-03 22:57:15.917 29621 29621 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-03 22:57:15.918 29621 29621 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
06-03 22:57:15.918 29621 29621 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-03 22:57:15.918 29621 29621 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-03 22:57:15.918 29621 29621 W System.err: 	at java.lang.Thread.run(Thread.java:761)
06-03 22:57:15.920 29621 29668 D librus-client-log: data fetched succesfully from https://api.librus.pl/2.0Attendances/Types
06-03 22:57:15.927 29621 29638 I art     : Background partial concurrent mark sweep GC freed 104562(4MB) AllocSpace objects, 3(336KB) LOS objects, 40% free, 8MB/13MB, paused 8.728ms total 198.699ms
06-03 22:57:15.943 29621 29658 D librus-client-log: data fetched succesfully from https://api.librus.pl/2.0HomeWorks/Categories
06-03 22:57:15.946 29621 29661 D librus-client-log: plugin handle
06-03 22:57:15.946 29621 29661 D librus-client-log: io.reactivex.exceptions.UndeliverableException: pl.librus.client.data.server.HttpException: Request to URL https://api.librus.pl/2.0/HomeWorks failed
06-03 22:57:15.947 29621 29663 D librus-client-log: data fetched succesfully from https://api.librus.pl/2.0Grades/Comments
06-03 22:57:15.966 29621 29664 D librus-client-log: data fetched succesfully from https://api.librus.pl/2.0/Lessons
06-03 22:57:15.988 29621 29677 D librus-client-log: plugin handle
06-03 22:57:15.988 29621 29677 D librus-client-log: io.reactivex.exceptions.UndeliverableException: pl.librus.client.data.server.HttpException: Request to URL https://api.librus.pl/2.0/Timetables?weekStart=2017-06-05 failed
06-03 22:57:16.029 29621 29669 D librus-client-log: plugin handle
06-03 22:57:16.030 29621 29669 D librus-client-log: io.reactivex.exceptions.UndeliverableException: pl.librus.client.data.server.HttpException: Request to URL https://api.librus.pl/2.0/Attendances failed
06-03 22:57:16.042 29621 29670 D librus-client-log: plugin handle
06-03 22:57:16.042 29621 29670 D librus-client-log: io.reactivex.exceptions.UndeliverableException: pl.librus.client.data.server.HttpException: Request to URL https://api.librus.pl/2.0/Timetables?weekStart=2017-05-29 failed
06-03 22:57:16.089 29621 29657 D librus-client-log: plugin handle
06-03 22:57:16.089 29621 29657 D librus-client-log: io.reactivex.exceptions.UndeliverableException: pl.librus.client.data.server.HttpException: Request to URL https://api.librus.pl/2.0Grades/Categories failed
06-03 22:57:16.125 29621 29656 D librus-client-log: plugin handle
06-03 22:57:16.125 29621 29656 D librus-client-log: io.reactivex.exceptions.UndeliverableException: pl.librus.client.data.server.HttpException: Request to URL https://api.librus.pl/2.0/SchoolNotices failed
```

**Comment by mimi89999** [comment]
Looks like some schools don't have lucky numbers on...

**Comment by tomikmar** [comment]
Do you have plans for new release/tag? It would be great if we could test this before the end of school year.
